import { DemoScenario } from './demo-context';

export const demoScenarios: DemoScenario[] = [
  {
    id: 'manufacturing',
    name: 'Manufacturing Company Demo',
    description: 'Heavy machinery shipping with special handling and PO payment.',
    expectedDuration: 5,
    demoData: {
      companyName: 'Heavy Industries Inc.',
      paymentMethod: 'purchase_order',
      packages: [
        {
          weight: '750',
          length: '48',
          width: '40',
          height: '72',
          description: 'Industrial Generator',
          declaredValue: '25000',
        },
      ],
    },
    steps: [
      {
        stepNumber: 1,
        title: 'Start Shipment',
        description: 'Navigate to the shipping page and enter initial details.',
        component: '/shipping',
        actions: [
          { type: 'navigate', target: '/shipping' },
          { type: 'wait', duration: 2000 },
          { type: 'fill', target: '#origin-contact-name', value: 'John Smith', animation: 'typing' },
          { type: 'fill', target: '#origin-contact-company', value: 'Heavy Industries Inc.', animation: 'typing' },
          { type: 'fill', target: '#origin-contact-phone', value: '555-0123', animation: 'typing' },
          { type: 'fill', target: '#origin-contact-email', value: 'shipping@heavyindustries.com', animation: 'typing' },
        ],
        validations: [],
      },
      {
        stepNumber: 2,
        title: 'Fill Origin Address',
        description: 'Enter the pickup address details.',
        component: '/shipping',
        actions: [
          { type: 'fill', target: '#origin-address', value: '1234 Industrial Blvd', animation: 'typing' },
          { type: 'fill', target: '#origin-city', value: 'Detroit', animation: 'typing' },
          { type: 'fill', target: '#origin-state', value: 'MI', animation: 'typing' },
          { type: 'fill', target: '#origin-zip', value: '48201', animation: 'typing' },
          { type: 'click', target: '#origin-commercial' },
        ],
        validations: [],
      },
      {
        stepNumber: 3,
        title: 'Fill Destination Address',
        description: 'Enter the delivery address details.',
        component: '/shipping',
        actions: [
          { type: 'fill', target: '#destination-contact-name', value: 'Sarah Johnson', animation: 'typing' },
          { type: 'fill', target: '#destination-contact-company', value: 'ABC Manufacturing', animation: 'typing' },
          { type: 'fill', target: '#destination-address', value: '5678 Factory Way', animation: 'typing' },
          { type: 'fill', target: '#destination-city', value: 'Chicago', animation: 'typing' },
          { type: 'fill', target: '#destination-state', value: 'IL', animation: 'typing' },
          { type: 'fill', target: '#destination-zip', value: '60601', animation: 'typing' },
          { type: 'click', target: '#destination-commercial' },
        ],
        validations: [],
      },
      {
        stepNumber: 4,
        title: 'Package Details',
        description: 'Enter package information.',
        component: '/shipping',
        actions: [
          { type: 'fill', target: '#package-weight-value', value: '750', animation: 'typing' },
          { type: 'fill', target: '[data-testid="dimension-length"]', value: '48', animation: 'typing' },
          { type: 'fill', target: '[data-testid="dimension-width"]', value: '40', animation: 'typing' },
          { type: 'fill', target: '[data-testid="dimension-height"]', value: '72', animation: 'typing' },
          { type: 'fill', target: '#package-declared-value', value: '25000', animation: 'typing' },
        ],
        validations: [],
      },
      {
        stepNumber: 5,
        title: 'Get Quotes',
        description: 'Submit the form to get shipping quotes.',
        component: '/shipping',
        actions: [
          { type: 'highlight', target: '[data-testid="get-quotes-button"]', duration: 1000 },
          { type: 'click', target: '[data-testid="get-quotes-button"]' },
          { type: 'wait', duration: 3000 },
        ],
        validations: [],
      },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare Demo',
    description: 'High-value, temperature-controlled medical equipment shipping.',
    expectedDuration: 6,
    demoData: {
      companyName: 'MediCare Logistics',
      paymentMethod: 'credit_card',
      specialHandling: ['temperature_control'],
      packages: [
        {
          weight: '150',
          length: '36',
          width: '24',
          height: '30',
          description: 'MRI Coil',
          declaredValue: '75000',
        },
      ],
    },
    steps: [
      {
        stepNumber: 1,
        title: 'Start Healthcare Shipment',
        description: 'Navigate to the shipping page and enter medical facility info.',
        component: '/shipping',
        actions: [
          { type: 'navigate', target: '/shipping' },
          { type: 'wait', duration: 2000 },
          { type: 'fill', target: 'input[name="senderName"]', value: 'MediCare Logistics', animation: 'typing' },
          { type: 'fill', target: 'input[name="senderPhone"]', value: '555-0456', animation: 'typing' },
          { type: 'fill', target: 'input[name="senderEmail"]', value: 'logistics@medicare.com', animation: 'typing' },
        ],
        validations: [],
      },
      {
        stepNumber: 2,
        title: 'Medical Equipment Details',
        description: 'Enter specialized medical equipment information.',
        component: '/shipping',
        actions: [
          { type: 'fill', target: 'input[name="weight"]', value: '150', animation: 'typing' },
          { type: 'fill', target: 'input[name="length"]', value: '36', animation: 'typing' },
          { type: 'fill', target: 'input[name="width"]', value: '24', animation: 'typing' },
          { type: 'fill', target: 'input[name="height"]', value: '30', animation: 'typing' },
          { type: 'fill', target: 'input[name="description"]', value: 'MRI Coil - Temperature Sensitive', animation: 'typing' },
          { type: 'fill', target: 'input[name="declaredValue"]', value: '75000', animation: 'typing' },
        ],
        validations: [],
      },
    ],
  },
];
